### ISSUE TITLE
WEB接口的登录问题

### ISSUE THREAD

**Issue by huskier** [PuzzledAlien/WeeklyReport#1]
现在编译和调试运行都可以了(.net core版本)，数据库的连接串如下（在Enterprise.Web.dll.config文件中），数据库已经配置为SQL授权访问，且启用了sa账户，并设置了密码。
```
 <connectionStrings>
    <add name="DefaultConnection" connectionString="Data Source=.;Initial Catalog=Enterprise;User Id =sa;Password=MY_PASSWD;" providerName="System.Data.SqlClient" />
  </connectionStrings>

```
进入登录界面后，
1. 默认账户admin不能登录，提示“账号或密码错误。”；
2. 点击“注册”按钮，进入注册页面完成信息填写后，按“注册”按钮显示“Error： 404”，没有更多信息了。

估计还有什么地方没设置对？
admin账户是不是在数据库端创建的？
“注册”对应的代码是不是有什么特殊处理？

切换到.NET Framework 4.8后，
1.  默认账户admin仍然不能登录，提示“账号或密码错误。”；
2. 进入注册页面点击“注册”按钮后出现异常：
System.IO.FileLoadException
  HResult=0x80131040
  Message=未能加载文件或程序集“System.Data.SqlClient, Version=4.6.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)

出现异常的代码如下：
```
        public bool Insert(object obj)
        {
            if (obj == null)
                return false;

            SqlExpressionArgs args = new SqlExpressionArgs();
            args.Type = SqlExpressionType.Insert;
            **SqlExpression sqlExpression = RelationalMappingUnity.GetSqlExpression(obj, args);**   //【异常语句】
            return ExcuteSqlExpression(sqlExpression) == 1;
        }
```

Thanks.

**Comment by PuzzledAlien** [comment]
是这样的，默认显示的账号 admin 和 密码 是展示，sql中不存在该账户数据。注册报错，应该是数据库没连接上。

**Comment by huskier** [comment]
“core版本注册报错是因为路由”这个问题修复之后终于可以“识得庐山真面目”，可以注册了！鉴于.net core是.net的未来，.net framework部分我就先不关注了。接下来进去之后的一些问题我另开一个issue吧。

多谢！
