### ISSUE TITLE
登录界面之后出现的问题（.net core的版本）

### ISSUE THREAD

**Issue by huskier** [PuzzledAlien/WeeklyReport#2]
登录界面后，我注册了一个个人账号，在试验各种功能的过程中，记录了如下问题：
1. 点击“设置”里面的“组织机构”会报错“Error: 404”；
2. 点击“设置”里面的“人员”会报错“Error: 404”；
3. 点击“设置”里面的“角色”里面的“新增”，加入新增项后点击“确定”按钮会报错“Error: 404”；
总之，“设置”里面的很多按钮点击了之后都会报错“Error: 404”。

点击“周报”里面的“填写”里面的“项目名称”和“子项目”名称以及“完成情况”都是乱的，看样子是直接的编码数字，但是查询里面这些列名对应的内容是正常显示的，比较怪异！

有空请帮忙看下吧（.net core版本的，后面我就不再关注.net framework 4.8的了）。

**Comment by PuzzledAlien** [comment]
404 是因为路由规则变动导致，已修复你提到的部分并全部处理了一遍，可能会有疏漏，如仍有 404，请提 issue 。
中文乱码的问题也已经修复。

**Comment by huskier** [comment]
多谢，我又遇到几个404，这次我弄了一个Pull Request，请审核。
