### ISSUE TITLE
关于部署的问题

### ISSUE THREAD

**Issue by huskier** [PuzzledAlien/WeeklyReport#4]
您好！.net core的版本除了在集成环境中调试，可否简单地部署到Linux服务器啊？

或者，能否用docker部署？

或者，有没有部署相关的比较简单的教程什么的？

多谢！

huskier

**Comment by PuzzledAlien** [comment]
https://docs.microsoft.com/zh-cn/aspnet/core/host-and-deploy/?view=aspnetcore-3.1

自然可以部署到 Linux服务器，并且还可以搭配SQL Server Linux 版。
