### ISSUE TITLE
dotnet publish后的独立程序localhost:5000/Home/Login可以访问，但IPAddress:5000/Home/Login不能访问

### ISSUE THREAD

**Issue by huskier** [PuzzledAlien/WeeklyReport#5]
dotnet publish后的独立程序localhost:5000/Home/Login可以访问，但IPAddress:5000/Home/Login不能访问，且对launchSettings.json做了如下改动。Publish到win-x64如此，Publish到linux-x64也是一样的效果，localhost字串好使，IP地址不好使。
```
    "Enterprise.Web": {
        "commandName": "Project",
        "launchBrowser": true,
        "applicationUrl": "http://0.0.0.0:5000;http://localhost:5000;",
        "environmentVariables": {
            "ASPNETCORE_ENVIRONMENT": "Development"
        }
```

**Comment by PuzzledAlien** [comment]
launchSettings.json 在 debug 时起效。运行时起作用的话，可以在配置文件中指定 url。请参考：https://docs.microsoft.com/zh-cn/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1#endpoint-configuration
