### ISSUE TITLE
dotnet publish到linux-x64的问题

### ISSUE THREAD

**Issue by huskier** [PuzzledAlien/WeeklyReport#6]
dotnet publish到linux-x64上之后，出现如下问题：
1. localhost:5000/Home/Login可以访问，且速度飞快，但IPAddress:5000/Home/Login不能访问；
2. 注册页面里面的验证码不正常，没显示，浏览器版本如下（我Linux是RHEL 7.x，浏览器都较老）：
   Chrome：Version 62.0.3202.75 (Official Build) (64-bit)
   Firefox：52.0 (64-bit）
3. 后来我在一个RHEL 8.x的虚拟机上试了，也是同1和2一样的问题，此时Firefox的版本为68.0。

说明：
程序虽然发布到了linux，但是数据库我还是连接的原来Windows上的，用了IP地址，做了协议设置。

**Comment by PuzzledAlien** [comment]
访问url配置：
https://docs.microsoft.com/zh-cn/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1#endpoint-configuration

**Comment by PuzzledAlien** [comment]
验证码的问题请参考：
https://docs.microsoft.com/en-us/answers/questions/21167/linux-app-service-systemdrawinggdiplus-threw-an-ex.html
```
apt-get update

apt-get install -y --allow-unauthenticated libx11-dev

apt-get install -y --allow-unauthenticated libc6-dev

apt-get install -y --allow-unauthenticated libgdiplus
```

**Comment by huskier** [comment]
So far so good. 现在Linux也运行正常了，可以用IP地址访问了。关于验证码的问题，等升级到RHEL 8.x后再说吧。
