### ISSUE TITLE
“设置”中的“人员”和“周报”中的“统计”下面的人员不一致

### ISSUE THREAD

**Issue by huskier** [PuzzledAlien/WeeklyReport#7]
“设置”中的“人员”和“周报”中的“统计”下面的人员不一致，在“设置”中的“人员”删除后，并没有同步到“周报”中的“统计”下面的人员中。

**Comment by PuzzledAlien** [comment]
已解决。需要执行sql修改存储过程。[WeeklyReport/issue_7.sql at master · PuzzledAlien/WeeklyReport](https://github.com/PuzzledAlien/WeeklyReport/blob/master/Data/issue_7.sql)
